### ISSUE TITLE
問題：Searching和Laravel scout的差異

### ISSUE THREAD

**Issue by ycs77** [xiaohuilam/searching#4]
如題，請問可否詳細說明這兩個搜索套件的差異?

**Comment by xiaohuilam** [comment]
As i know so far, `Laravel scout` provides a way to write your own search engine, and this `searching` package provides you a way to use the scaffold search functions, so, can you feel these two things' difference?

In another word, with Laravel scout, you need to build your own user-interface, such as html, js, and style codes. but you can do more with it.
and this `searching` package, is a simple solution for multi model searching(if using scout, i think you might need little time to achieve), and for the effort saving, you can use the already wrote ui, even routes、controllers is already defined what you need to do is just to implements each interface functions for every models. but, you need to know that first, it does not including many features scout provides (such as Algolia/Elasticsearch).

If necessary, i will list the diffs later in the readme or wiki.

**Comment by ycs77** [comment]
謝謝您的解釋！
